### ISSUE TITLE
Crop image on ImageContainer and data

### ISSUE THREAD

**Issue by ccruizm** [theislab/squidpy#337]
Good day,

Thanks for developing this great tool. I want to use tangram to deconvolve each spot, but I have problems cropping using the same coordinates on the ImageContainer object and the data with the ST data. I do not understand how to subset the ST data to match the image. When I use `crop_coor` within the scanpy workflow to display the plot (for instance `sc.pl.spatial(adata, img_key="hires", color="clusters",  crop_coord=[15000, 25000, 20000, 10000], alpha=0, size=1.3)`) and try to use those on the ImageContainer, it does not seem to work. How can I subset the data and crop the image to match the same coordinates?

Thanks in advance!

**Comment by giovp** [comment]
hi @ccruizm ,

thanks for your interest in squidpy! in #324 we are working toward a method that makes it convenient for subsetting anndata according to the imgcontainer crop (give us another 2 weeks to this one in master and well documented with example/tutorial).

what's the type of cropping you are trying to achieve? with more details I could provide you witha working example for the time being.

**Comment by michalk8** [comment]
Implemented via  #324 (on the `dev` branch) as e.g.:
```python
adata = ...
img = sq.im.ImageContainer(....)
adata_subset = img.crop_corner(0, 0, (1000, 1000)).subset(adata)
```

**Comment by ccruizm** [comment]
Thank you! I used the implemented approach mentioned by @michalk8, and it works nicely!

The segmentation usually gives some false positives, and we have tried to use other tools to overcome this. I would like to know how to input info (and which format) generated from other tools into the data object to use these segmentation features instead. I saw in #324 that there seems to be a better segmentation method, similar to the tool we are currently using to do that, as seen in the image below. Is there a tutorial to use that approach? 

<img width="681" alt="Screenshot 2021-05-04 at 11 02 12" src="https://user-images.githubusercontent.com/37718031/118466243-f305e700-b702-11eb-8fda-3a793a550c40.png">

Attached the output file from the tool we are currently using. 

Thanks for your help!

[spot_info.csv](https://github.com/theislab/squidpy/files/6492841/spot_info.csv)

**Comment by giovp** [comment]
hi @ccruizm ,

we are gonna release `squidpy 1.2` sometime next week. Meanwhile, if you install it with `pip install -e .` from the `dev` branch, you can already try out the new tutorials.
We have added tutorials to work with Stardist and Cellpose:

- https://squidpy.readthedocs.io/en/latest/external_tutorials/tutorial_cellpose_segmentation.html
- https://squidpy.readthedocs.io/en/latest/external_tutorials/tutorial_stardist.html

let us know if that helps, they should also be general enough to help you plug in your own pretrained/fine tuned favourite model.

**Comment by ccruizm** [comment]
This looks great!!! Thank you very much! will give it a try

**Comment by giovp** [comment]
from #339 comment I understand this is solved. I'm gonna close this but feel free to reopen if needed.

you can also try the new segmentation tutorials from here: https://squidpy.readthedocs.io/en/latest/tutorials.html#external-tutorials

**Comment by nsauerwald** [comment]
I know this issue has been closed, but I am having trouble with the same problem still. The .subset() function consistently gives me an AnnData object with n_obs = 0, and I can't figure out why.

`adata = sc.read_visium(...)
img = sq.im.ImageContainer(adata.uns['spatial'][libraryid]['images']['hires'])
img_crop = img.crop_corner(x=xx, y=yy, size=s)
adata_subset = img_crop.subset(adata)
print(adata)
print(adata_subset)`

gives

`AnnData object with n_obs × n_vars = 1434 × 19465
    obs: 'in_tissue', 'array_row', 'array_col'
    var: 'gene_ids', 'feature_types', 'genome'
    uns: 'spatial'
    obsm: 'spatial'
View of AnnData object with n_obs × n_vars = 0 × 19465
    obs: 'in_tissue', 'array_row', 'array_col'
    var: 'gene_ids', 'feature_types', 'genome'
    uns: 'spatial'
    obsm: 'spatial'`
    
Any advice? I've also tried the crop_coord input to scanpy.pl.spatial, which just shows a blank square.

**Comment by RYY0722** [comment]
Hey @nsauerwald ! Have you solved that problem? I got constant blank as well. Would you please give me some help? Thank you very much!

**Comment by giovp** [comment]
hi @RYY0722 @nsauerwald I believe the problem is because the crop you are selecting does not contain any observations. This is revealed by the fact that plotting also gives an empty crop. Are you sure you selected the coordinates for the bounding box correctly?

**Comment by RYY0722** [comment]
Hi @giovp thank you so much for your quick reply!
But I don't think that the region that I am cropping is empty.
Firstly,
`img = sq.im.ImageContainer(adata.uns["spatial"]['c']["images"]["hires"], layer='image', library_id='c')`
1. by calling   upper_img.show(layer='image'), I can see that it contains what I want.
2. By calling 
`upper_img = img.crop_corner(y=0.0, x=0.0, size=img.shape)`
`upper_img.subset(adata)`
, where I am subsetting the whole image. 
it returns
`View of AnnData object with n_obs × n_vars = 0 × 36601`

However, 
`img.subset(adata)` works,
 and it gives me AnnData object with n_obs × n_vars = 827 × 36601

**Comment by RYY0722** [comment]
@giovp Sorry that I still cannot solve this wired problem. Would you please help me look into that? Thanks a lot!

**Comment by RYY0722** [comment]
@giovp @nsauerwald Hi! I think that it is caused by that I didn't pass the scale factor when I create the image container.
It should be 
`scale = adata.uns['spatial']['c']["scalefactors"]['tissue_hires_scalef']`
`img = sq.im.ImageContainer(adata.uns["spatial"]['c']["images"]["hires"], layer='image', library_id='c', scale=scale)`
